ARG IMAGE_NAME=registry.access.redhat.com/ubi8/ubi-minimal:8.4
ARG ARCH
FROM ${IMAGE_NAME}

COPY microshift /usr/bin/microshift
RUN chmod +x /usr/bin/microshift

RUN microdnf install -y \
    libnetfilter_conntrack libnfnetlink libpcap \
    policycoreutils-python-utils \
    && microdnf clean all

# Error with iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
# Switch to iptables-1.6.2 that is compatible with iptables on Jetson Nano with Ubuntu 18.04
RUN rpm -v -i --force https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/28/Everything/aarch64/os/Packages/i/iptables-libs-1.6.2-2.fc28.aarch64.rpm \
    https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/28/Everything/aarch64/os/Packages/i/iptables-1.6.2-2.fc28.aarch64.rpm

ENTRYPOINT ["/usr/bin/microshift"]
CMD ["run"]
